modify deleteNote() and functions.php so that the server will let the user delete a note
-modify deleteNote(). From my notes: "Using .ajax jquery tool
This is how the frontend will communicate with the server. We'll use something like $.ajax(object)
The object it needs
beforeSend: callback function—with the right function, it lets you add security data to your request before sending it to the server so that wordpress knows that it's actually you
Making it work
In the callback function, you'll need to use something like 'xhr' as a pre-defined parameter that we're given. Then in the actual code, you'll do something like xhr.setRequestHeader('X-WP-Nonce', universityData.nonce)
Setting up universityData.nonce
For our javascript to actually access the security code, we need to add something in functions.php. We'll add something like 'nonce' => wp_create_nonce('wp_rest') inside of a wp_localize_script()
url: string—the URL you're trying to reach
type: string—what request you want to make at that URL. For example, a POST request
success: callback function—what you want to do if it succeeds
error: callback function—what you want to do if it fails"

-tell wordpress to create a nonce designed to tell nonce that the user can access rest API and use wp_localize_script to make it available to our javascript code